import math


TOTAL_PROCESS_MINUTES = 1440
STARTUP_FILL_MINUTES = 1000
DEFAULT_DECISION_INTERVAL = 5

AVAILABLE_CONTROL_MINUTES = TOTAL_PROCESS_MINUTES
DEFAULT_CONTROL_STEPS = math.ceil(AVAILABLE_CONTROL_MINUTES / DEFAULT_DECISION_INTERVAL)
